//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.18 at 03:04:16 PM CEST 
//


package com.agent.app.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.agent.app.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.agent.app.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link FacilityTypeWS }
     * 
     */
    public FacilityTypeWS createFacilityTypeWS() {
        return new FacilityTypeWS();
    }

    /**
     * Create an instance of {@link LocationWS }
     * 
     */
    public LocationWS createLocationWS() {
        return new LocationWS();
    }

    /**
     * Create an instance of {@link RoleWS }
     * 
     */
    public RoleWS createRoleWS() {
        return new RoleWS();
    }

    /**
     * Create an instance of {@link UserWS }
     * 
     */
    public UserWS createUserWS() {
        return new UserWS();
    }

    /**
     * Create an instance of {@link FacilityWS }
     * 
     */
    public FacilityWS createFacilityWS() {
        return new FacilityWS();
    }

    /**
     * Create an instance of {@link AppointmentWS }
     * 
     */
    public AppointmentWS createAppointmentWS() {
        return new AppointmentWS();
    }

    /**
     * Create an instance of {@link ReservationWS }
     * 
     */
    public ReservationWS createReservationWS() {
        return new ReservationWS();
    }

    /**
     * Create an instance of {@link RatingWS }
     * 
     */
    public RatingWS createRatingWS() {
        return new RatingWS();
    }

    /**
     * Create an instance of {@link AgentFacilitiesWS }
     * 
     */
    public AgentFacilitiesWS createAgentFacilitiesWS() {
        return new AgentFacilitiesWS();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

}
